{
    "name": "Accounting",
    "summary": "Install accounting modules",
    "author": "Onestein",
    "category": "Accounting",
    "version": "16.0.1.0.0",
    "license": "AGPL-3",
    "depends": [
        "container_install",
        "account",
        "account_payment_mode",
        "account_payment_order",
        "account_payment_partner",
        "account_fiscal_position_vat_check",
        "account_invoice_constraint_chronology",
        "account_invoice_line_default_account",
        "account_journal_lock_date",
        "account_lock_date_update",
        "account_move_print",
        "account_usability",
        "base_vat_optional_vies",
        "account_reconcile_oca",
        "account_statement_base",
        "account_payment_sale",
        "product_margin",
        "account_financial_report",
        "product_category_product_link",
        "account_statement_import_camt",
        "account_statement_import_camt54",
        "account_statement_import_file_reconcile_oca",
        "account_period_auto_create",
        "account_statement_import_online_ponto",
        "account_statement_import_online_ponto_statement_creation_mode",
        "account_statement_import_sheet_file",
        "account_statement_import_sheet_file_sheet_mappings",
        "account_move_line_attachment_preview",
        "account_configuration",
        "account_invoice_overdue_reminder",
        "account_move_line_tax_editable",
        "account_move_tier_validation",
        "account_statement_import_online_paypal",
        "contract",
        "contract_payment_mode",
        "currency_rate_update",
        "l10n_nl_rgs",
        "l10n_nl_rgs_usability",
        "l10n_nl_rgs_mis_report",
        "l10n_nl_rgs_account_financial_report",
        "l10n_nl_rgs_asset",
        "l10n_nl_bank",
        "l10n_nl_xaf_auditfile_export",
        "l10n_nl_tax_statement",
        "l10n_nl_tax_statement_date_range",
        "l10n_nl_tax_statement_icp",
        "mollie_account_sync",
        "payment_mollie_official",
    ],
}
