from . import res_users
from . import res_partner
from . import ir_mail_server
from . import restrict_mixin
from . import ir_module_module
from . import payment_provider
from . import res_config_settings
from . import oauth_provider
from . import auditlog_rule
from . import auditlog_log
from . import auditlog_log_line
from . import auditlog_autovacuum
from . import ir_cron
from . import server_config
from . import fs_storage
