{
    "name": "Essentials Installation",
    "summary": "Installs essential modules",
    "author": "Onestein",
    "website": "https://onestein.nl",
    "category": "Technical",
    "version": "18.0.1.0.0",
    "license": "AGPL-3",
    "data": ["security/security.xml"],
    "depends": [
        "base_address_extended",
        "base_technical_features",
        "fs_storage",
        "fs_attachment",
        "fs_storage_backup",
        "web_responsive",
        "disable_odoo_online",
        "base_fontawesome_web_editor",
        "auth_oidc",
        "container_accessibility",
        "report_qr",
        "report_qweb_element_page_visibility",
        "report_qweb_parameter",
        "report_qweb_pdf_watermark",
        "report_wkhtmltopdf_param",
        "report_xlsx",
        "report_xlsx_helper",
        "date_range",
        "base_tier_validation",
        "digest_configuration",
        "payment_custom",
        "payment_demo",
        "partner_firstname",
        "web_no_bubble",
        "web_hierarchy",
        "base_customer_company",
        "base_customer_user",
        "base_onboarding",
        "spreadsheet_dashboard_oca",
        "spreadsheet_oca_ux",
        "remove_odoo_enterprise",
        "remove_enterprise_shipping_connector",
        "base_import_debranding",
        "digest_disable",
        "partner_external_map",
        "partner_external_map_usability",
        "fetchmail_notify_error_to_sender",
        "product_category_product_link",
        "mail_branding",
        "mail_debrand",
        "base_module_bundle",
        "mail_attach_existing_attachment",
        "partner_contact_department",
        "mail_tracking",
        "mail_raise_log_level",
        "sentry",
        "operating_unit",
        "analytic_operating_unit",
        "report_qweb_operating_unit",
        "base_name_search_improved",
        "partner_contact_access_link",
        "server_action_mass_edit",
        "web_refresher",
        "web_search_with_and",
        "portal_odoo_debranding",
        "web_dialog_size",
        "iap_alternative_provider",
        "web_responsive_attachment_preview",
        "base_geolocalize",
        "web_branding",
        "base_branding",
        "calendar",
        "calendar_branding",
        "release_note",
        "auth_password_policy",
    ],
    "bundle": True,
}
