{
    "name": "Essentials Installation",
    "summary": "Installs essential modules",
    "author": "Onestein",
    "website": "https://onestein.nl",
    "category": "Technical",
    "version": "16.0.1.0.0",
    "license": "AGPL-3",
    "depends": [
        "fs_storage",
        "fs_attachment",
        "fs_storage_backup",
        "web_responsive",
        "disable_odoo_online",
        "base_fontawesome",
        "auth_oidc",
        "container_accessibility",
        "report_qr",
        "report_qweb_parameter",
        "report_wkhtmltopdf_param",
        "report_xlsx",
        "report_xlsx_helper",
        "date_range",
        "base_tier_validation",
        "digest_configuration",
        "payment_custom",
        "payment_demo",
        "l10n_nl_bank",
        "l10n_nl_postcode",
        "partner_firstname",
        "web_no_bubble",
        "base_customer_company",
        "base_customer_user",
        "base_onboarding",
        "spreadsheet_dashboard_oca",
        "spreadsheet_oca_ux",
        "partner_country_default_nl",
        "remove_odoo_enterprise",
        "base_import_debranding",
        "digest_disable",
        "partner_external_map",
        "fetchmail_notify_error_to_sender",
        "base_municipality",
        "product_category_product_link",
    ],
}
