{
    "name": "Website & Blog",
    "summary": "Build a website",
    "author": "Onestein",
    "website": "https://onestein.nl",
    "category": "Website",
    "version": "16.0.1.0.0",
    "license": "AGPL-3",
    "depends": [
        "website",
        "website_blog",
        "website_odoo_debranding",
        "website_onboarding",
        "website_share_blogger",
        "website_share_diaspora",
        "website_share_filter_option_blogger",
        "website_share_filter_option_diaspora",
        "website_share_filter_option_friendica",
        "website_share_filter_option_mastodon",
        "website_share_filter_option_pleroma",
        "website_share_filter_option_reddit",
        "website_share_filter_option_skype",
        "website_share_filter_option_snapchat",
        "website_share_filter_option_technical",
        "website_share_filter_option_telegram",
        "website_share_filter_option_tumblr",
        "website_share_filter_option_wordpress",
        "website_share_friendica",
        "website_share_mastodon",
        "website_share_pleroma",
        "website_share_reddit",
        "website_share_skype",
        "website_share_snapchat",
        "website_share_telegram",
        "website_share_tumblr",
        "website_share_wordpress",
        "website_two_steps_share_technical",
        "website_snippet_dynamic_link",
        "website_snippet_openstreetmap",
    ],
    "purge_depends": True,
}
