name: tests

on:
  pull_request:
    branches:
      - "16.0*"
  push:
    branches:
      - "16.0"

jobs:
  test:
    runs-on: ubuntu-22.04
    container: docker.io/onestein/odoo-ci:16.0
    name: Odoo
    services:
      postgres:
        image: postgres:12.0
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Aggregate
        run: gitaggregate -c repos.yaml
      - name: Install external dependencies
        run: pip3 install -r requirements.txt
      - name: Pack
        run: python3 scripts/pack.py --location . --package-file "package.txt" --destination package
      - name: Run tests
        run: oca_run_tests
        env:
          ADDONS_DIR: package
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
