name: tests

on:
  pull_request:
    branches:
      - "16.0*"
  push:
    branches:
      - "16.0"

jobs:
  test:
    runs-on: ubuntu-22.04
    container: docker.io/onestein/odoo-ci:16.0
    name: Odoo
    services:
      postgres:
        image: postgres:12.0
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: |  # https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints 
            github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
            github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
            github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      - name: Aggregate
        run: gitaggregate -c repos.yaml
      - name: Ensure correct odoo version
        run: |
          rm -rf /opt/odoo/odoo
          rm -rf /opt/odoo/addons
          rm -f /opt/odoo/requirements.txt
          cp -r odoo/odoo /opt/odoo/odoo
          cp -r odoo/addons /opt/odoo/addons
          cp odoo/requirements.txt /opt/odoo/requirements.txt
          pip install -r /opt/odoo/requirements.txt
      - name: Install external dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install odoo-test-helper
      - name: Pack
        run: python3 scripts/pack.py --location . --package-file "package.txt" --destination package
      - name: Initialize test db
        run: oca_init_test_database
        env:
          ADDONS_DIR: package
          EXCLUDE: account_financial_consolidation_report,account_statement_import_file_reconcile_oca,agreement_extended,helpdesk_ticket_custom_priority,management_dashboard,pm_migration_custom,project_budget_management,project_management_security,project_scrum_agile,project_scrum_agile_extended,project_team_leave_management,project_timesheet_management,theme_onestein,project_timeline_hr_timesheet,container_s3,l10n_nl_rgs_usability,l10n_nl_rgs_account_financial_report,mis_builder_budget,partner_country_default_nl,accountancy_install,community_org_install,container_install_basis,container_install_standard,project_org_install,services_org_install,trade_org_install,university_org_install,auditlog,fs_storage,fs_attachment,report_xlsx,base_menu_visibility_restriction,fs_storage_backup,queue_job,base_municipality,helpdesk_mgmt,account_invoice_constraint_chronology,account_spread_cost_revenue,project_sequence,base_vat_optional_vies,l10n_nl_rgs_asset,account_banking_mandate_contact,account_banking_sepa_credit_transfer,hr_timesheet_sheet,multi_company_disable,account_financial_report,account_asset_management,account_chart_update,account_journal_lock_date,account_move_line_tax_editable,currency_rate_update,account_asset_management_template,account_reconcile_oca,account_payment_order,fs_storage_backup,mis_builder,l10n_nl_rgs_asset,l10n_nl_rgs_mis_report,account_banking_sepa_credit_transfer
          ODOO_VERSION: "16.0"          
      - name: Run tests
        run: oca_run_tests
        env:
          ADDONS_DIR: package
          EXCLUDE: account_financial_consolidation_report,account_statement_import_file_reconcile_oca,agreement_extended,helpdesk_ticket_custom_priority,management_dashboard,pm_migration_custom,project_budget_management,project_management_security,project_scrum_agile,project_scrum_agile_extended,project_team_leave_management,project_timesheet_management,theme_onestein,project_timeline_hr_timesheet,container_s3,l10n_nl_rgs_usability,l10n_nl_rgs_account_financial_report,mis_builder_budget,partner_country_default_nl,accountancy_install,community_org_install,container_install_basis,container_install_standard,project_org_install,services_org_install,trade_org_install,university_org_install,auditlog,fs_storage,fs_attachment,report_xlsx,base_menu_visibility_restriction,fs_storage_backup,queue_job,base_municipality,helpdesk_mgmt,account_invoice_constraint_chronology,account_spread_cost_revenue,project_sequence,base_vat_optional_vies,l10n_nl_rgs_asset,account_banking_mandate_contact,account_banking_sepa_credit_transfer,hr_timesheet_sheet,multi_company_disable,account_financial_report,account_asset_management,account_chart_update,account_journal_lock_date,account_move_line_tax_editable,currency_rate_update,account_asset_management_template,account_reconcile_oca,account_payment_order,fs_storage_backup,mis_builder,l10n_nl_rgs_asset,l10n_nl_rgs_mis_report,account_banking_sepa_credit_transfer
          ODOO_VERSION: "16.0"
      - name: Prepare report
        run: coverage xml -o report.xml --data-file .coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Run scripts
        env:
          DOMAIN: https://onestein.nl
          ADMIN_USER_PWD: admin
          CHANGE_ADMIN_USER_PWD: admin
          SETUP_SMTP: "false"
          SMTP_HOST: "false"
          COMPANY_EMAIL: info@onestein.nl,
          PREPARE_CUSTOMER_USER: "true"
          UPDATE_COMPANY: "false"
          KEYCLOAK_URL: https://keycloak.onestein.nl
          KEYCLOAK_REALM: main
          KEYCLOAK_CLIENT_ID: odoo
          KEYCLOAK_CLIENT_SECRET: odoo
          KEYCLOAK_RESELLER_REALM: reseller
          KEYCLOAK_RESELLER_CLIENT_SECRET: odoo
        run: |
          ./scripts/run.sh